# Generated by Django 2.0.5 on 2018-11-06 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restful_api', '0003_vegetation'),
    ]

    operations = [
        migrations.CreateModel(
            name='solvedMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osmID', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('answer', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('creator',),
            },
        ),
        migrations.CreateModel(
            name='UserAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koins', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('experience', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('towers', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('tower_range', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('sight_range', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('creator',),
            },
        ),
        migrations.RemoveField(
            model_name='userarea',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Vegetation',
        ),
        migrations.DeleteModel(
            name='UserArea',
        ),
    ]
