# Generated by Django 2.0.5 on 2018-11-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0004_auto_20181106_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedmission',
            name='answer',
            field=models.CharField(max_length=99),
        ),
    ]
