# Generated by Django 2.0.5 on 2018-11-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0005_auto_20181106_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedmission',
            name='solved_by',
            field=models.CharField(default=0, max_length=99),
        ),
        migrations.AddField(
            model_name='solvedmission',
            name='timestamp',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
        ),
    ]
