# Generated by Django 2.0.5 on 2018-11-11 18:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0007_placedtower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedtower',
            name='location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=15, max_digits=18), size=2),  # noqa
        ),
    ]
