# Generated by Django 2.0.5 on 2018-11-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0009_placedlandmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattributes',
            name='landmarks',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
