sudo: required
services:
- docker
language: python
python:
- 3.6
addons:
  apt:
    firefox: latest
install:
- pip install -U docker-compose
- docker-compose build backend
- "(cd client && npm install)"
script:
- docker-compose run --rm backend flake8 .
- docker-compose run --rm backend ./manage.py test restful_api
- "(cd client && MOZ_HEADLESS=1 npm test)"
- docker-compose -f docker-compose.push.yml build --pull
- echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_ACCOUNT" --password-stdin
- docker-compose -f docker-compose.push.yml push
env:
  global:
  - secure: rHykCjtM38Nf5BiZyzQQbBTVLmHr0LvVHM6b6d66A4+Y4snGO3YwSdGV0aUDDVuR8Vf3lmRUwi+Wio6ksBCh0VZ/611nfEvZVJ+wjbe9URFKc3Rb5R9KDvM2104qeyP/2fhB1la9px48lFw4ofZVicNlIgcIqREAVUYRH0wv7SsQVcNOrq2TAoFmGQgJLBPmJn4eB6y4HvWvlLmtD7NZ2wbAf4Lj0tUePd4AwsOBYb77zGRt+YLHHPrfowJAh++7QhwcQELdtqhWXZ70LAswC77YpJUxHBY6iP+fmZqjbxncLiuWJLkuQphhmZIyFQ7rrhVNK9gjLZ7tGw7N0rDpICu6FoIrsv7cYUs1abixaRyi5klwV9Tj8VEtvwqqHENx4ofReV6KOINEpezycK6ZFZDj1N5PyLn19QkGsmDekezceRtLP4sMrvN8iI0m05N4AIkKZm3S+dAmYvvizhTEyHum1yxMAUt/thuTcjomnhtdYFNhs3q31A0K2+c7jcr7bovs0C+MXel1SBXHOaUODRAl7kjeKQ4SxMQQHAA5boG+MMlsoZsOqbQcr5WLf7cnzAvvCeUvKBxnsC2BxOWH0Hgf6+yOL6RlPYhoLtudwj1tuH2selEURweWVwhf+7LwvPDoKTMlF1GQzffMVUfDdqjmC2pFit0atzlHJbf57/0=
  - secure: vmPqkzFbewf5iRRHfNaMWxABXeBBO3b61nOkv4Wbw5v/XgIgn5jQ0fGvF4uTFdY976Bdhnj35ce1G+NVFRa8NmDFnFTcM8zkHX+JmJfWTyl87ptsBwfNX2yJRGfgAp+JEqa5b4RazG/hmqMdcvxROILvx+CNnmNtIpMBC/4H3Q+c5r2J+MpJKCd82orZ/SNoZ01u2Uq426GLOdU9H1fuvH590moAklBFd86YysYT9b0rDt6y2EFUM5zEYzerWXEaoS6QaKQSwxWSKIuV5b0VpGIzEPMCQcdF+GMHLhT1SrFoN4SHn5sMNSE7RyXlgS4CwqRiJw/GfxCsEYXEaw7LC+/H11P0bA9FXfCaah/9YHJAEeoAHEI7phpVXBATKYI8CM+T6IFBvO+bpMjcQE3Hrccy9/Jqhsxlmf+HNPrfA7RkPW6OXDeIJPoQjvJiDzmR0eFv8I581P1Uyu0RTFPEgRzEjLzQ1RvyUmhXsSrLuuZuK+95RhCEqrTDZTi1XwEHqGxWeEozA08E4qhZD5ZkBWeov+lQb4bWrJcCDbIdQZlW4owBkmaCvZi44wy4ZgAVjBxnFJGOSrF+sAzMAFpAx5Nda1BAqUlMjttBDXsPgTw+ieDsyHaUuz+D80MBFrFkrqYGLVY5cwdQVPtPrzyiNxF58yyIrZukNiQ/Z2VlHaw=
