sudo: required
services:
- docker
language: python
python:
- 3.6
addons:
  apt:
    firefox: latest
install:
- pip install -U docker-compose
- docker-compose build backend
- "(cd client && npm install)"
script:
- docker-compose run --rm backend flake8 .
- docker-compose run --rm backend ./manage.py test restful_api
- "(cd client && MOZ_HEADLESS=1 npm test)"
- docker-compose -f docker-compose.push.yml build --pull
- echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_ACCOUNT" --password-stdin
- docker-compose -f docker-compose.push.yml push
env:
  global:
  - secure: tzvG2XuhsrxYWsWFXD8e09YcFYKXAcTEm3iIrcopCWN4qt58+ZTqtDdiO9tueUixIJqNmA7ui5oO2ff3MyquAXcekEBVYn1zpaQY5QGWTTWzEBSU/2JioFm8cE1C2BUsq7aty0rDiq6nyOxpjAcuh6f+blT5ZJXVTKOV50WIVZm7oO3mi0xAMiINDyp9zg3nLS+duIJjBC9kc8ScqDoS9fTjO1g1mk+uadVTtc59crjTsfoZwlKzrIFP3PRPOf9FkhT9jtrX80WWDwFW9tJQjjFyXcXfZrUflIq7psKGDmrzWlJkh4CK/Fdfc7HiGLeMCfq35aM0WPHTDkm1HUHsWL5AfHVSiRYa7GlmCxsoz2Nvs9rU37OAMNHEhz+I9W9YM3SRoEXeAfDvOScKPQ4AdnIxc5mwt6SS1FCDppjedNhEWA6zMcEpRX/uKBmm0QLTyOCMd2Sl/Lh5n0pZ0F2OlNAzwr+H1JKU9LAOXlkidCNgmQ9wAxWVTtJy/qJOZpVG1imcaCGWhbRB+WVxAuWMNy9IX5+x+vLx9/KHaYuv0Ud+rat4zxlwc30JvtY0/g/v5k23MuMU5jzO3ixva6LQ/7v0b3EKqM/usxgh+/gOf5E4f5AWSaPkkctousEPST0lnsRsfGunbzWbb10BIAMPX1CQEZlGLJrTV3cjP+LV4vo=
  - secure: QLEW/cKnW/vkhMydm3mo2cN/b1ZrK1VhIAMWkYwFpEwBOyIPbRsBThCmgyB8J82j3P2TGozyM4/EL+Vp/jZFv1aI8W/W1ylxTfXvdbjR0qaVFK8gT/o7dcvjUBkRhwdQEeUH4aZRH1UR0u6mnWiOSpliyOVRap4anivCfpumT9roLvyNSMNEShl0dOnpVQ7YZOfTclGY03qFwaw4vzx00HH3VOEUe5/XlzJ96vRx9g9ZghvnhRk07kmepb28qa0xdSw+FGQRM68R2TjMvtR+8vU6S+R5d5+Zbum1W1uJUlMTfymTvhj8Lpaxc8aev0lW4uRwDW8Udgsxg7gdsH59+OqYjxLK/LJNUI6itt4cpXvVvH5cCVEQbPma2pC9853PW5m7X4DPVLj8xtg4b1UyDjbbGP7PUp7QjOGdgv5aGIATKkDipcSbAWkeoGIMaBMjTbBdYkBomR9YFLX1N+3NnoygJ7STHNHbbQODN6vpFGAtQ+VwQlrIoL1rh9oEq1ptZWXRGGrm7eCHA5ev857G2BsYwu8CL57lbNU+zqg4+DLuB/gJPu4aVkIZScHnbf8YyT24K1iccx4F719IC2aWWIAz6+XNGyy0JEIC7+Ndavbpm7bLQlJ7hwvwvjic9ktTowSqYOszQ5gY7msc6xoxD3BWj9J+ctZlwZim0MjJsIE=
