version: '3.5'
services:
  frontend:
    image: dschmide/proofofkortzept-client
    build:
      context: client
      dockerfile: Dockerfile.production
  backend: &backend
    image: dschmide/proofofkortzept-backend
    build: backend
  nginx:stable-alpine:
    image: dschmide/nginx-https-proxy
    build: .
networks:
  default:
