version: '3.5'
services:
  frontend:
    image: proofofkortzept/map-frontend
    build:
      context: client
      dockerfile: Dockerfile.production
  backend: &backend
    image: proofofkortzept/map-api
    build: backend
networks:
  default:
